services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      OPENCHARGEMAP_API_KEY: ${OPENCHARGEMAP_API_KEY}
      OPENCAGE_API_KEY: ${OPENCAGE_API_KEY}
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
